stages:
  - build
  - deploy

variables:
  REGISTRY_HOST: "5.144.176.74:30050"
  REGISTRY_USER: "gitlab"
  REGISTRY_PASSWORD: "IuM0DYTEfPZuSa9"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

.before_docker: &before_docker
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false", "--insecure-registry=5.144.176.74:30050"]
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin $REGISTRY_HOST

# Сборка и пуш фронтенда
build-and-push-frontend:
  stage: build
  <<: *before_docker
  script:
    - docker build -t $REGISTRY_HOST/frontend:latest ./client
    - docker push $REGISTRY_HOST/frontend:latest

# Сборка и пуш бэкенда
build-and-push-backend:
  stage: build
  <<: *before_docker
  script:
    - docker build -t $REGISTRY_HOST/backend:latest ./server
    - docker push $REGISTRY_HOST/backend:latest

# Деплой в K8S
deploy:
  stage: deploy
  image: bitnami/kubectl:1.10.11-ol-7
  script:
    - kubectl apply -f k8s/
  needs:
    - build-and-push-frontend
    - build-and-push-backend
