stages:
  - build
  - push
  - deploy

variables:
  REGISTRY_URL: "http://5.144.176.74:30050"
  REGISTRY_USER: "gitlab"
  REGISTRY_PASSWORD: "IuM0DYTEfPZuSa9"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

.before_docker: &before_docker
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin $REGISTRY_URL

# Сборка фронтенда
build-frontend:
  stage: build
  <<: *before_docker
  script:
    - docker build -t $REGISTRY_URL/frontend:latest ./client

# Сборка бэкенда
build-backend:
  stage: build
  <<: *before_docker
  script:
    - docker build -t $REGISTRY_URL/backend:latest ./server

# Пушим фронтенд
push-frontend:
  stage: push
  <<: *before_docker
  script:
    - docker push $REGISTRY_URL/frontend:latest
  needs:
    - build-frontend

# Пушим бэкенд
push-backend:
  stage: push
  <<: *before_docker
  script:
    - docker push $REGISTRY_URL/backend:latest
  needs:
    - build-backend

# Деплой в K8S
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s/
  needs:
    - push-frontend
    - push-backend