server {
    listen 80;
    server_name kashlevar.ru www.kashlevar.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kashlevar.ru www.kashlevar.ru;

    ssl_certificate     /etc/letsencrypt/live/kashlevar.ru/tls.crt;
    ssl_certificate_key /etc/letsencrypt/live/kashlevar.ru/tls.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|svg|ttf|eot|mp4|webm|ogg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    error_page 404 /index.html;
}
