server {
    listen 80;
    server_name api.kashlevar.ru www.api.kashlevar.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.kashlevar.ru www.api.kashlevar.ru;

    ssl_certificate     /etc/letsencrypt/live/api.kashlevar.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.kashlevar.ru/privkey.pem;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|svg|ttf|eot|mp4|webm|ogg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
